### ISSUE TITLE
Update the code to retrieve the list of the users who like the tweet and the users who retweet the tweet

### ISSUE THREAD

**Issue by davistamu** [jonbakerfish/TweetScraper#11]
I was wondering whether the code can be updated to retrieve the list of the users who like the tweet, the users who retweet the tweet, and the users who are mentioned in the tweet. if someone can do that, please share the approach with us. Thank you very much! @MathiasDesch

**Comment by MathiasDesch** [comment]
TweetScrapper is built on the top of Twitter search page in order to get rid of rate limitations. The Twitter search does not allow to look for likes and so on. I guess you could have to approach then :
- decide you can deal with the rate limitations and use the Twitter api and an other python project wrapping it.
- try to follow the links in scrapped tweets giving the list of users that liked or retweet and then parse this new page. It seems doable but you need to ensure that you are getting the full list of users and that the result is consistent.

I'll try to give a look and give you more insights.

**Comment by davistamu** [comment]
Thank you so much for your help. I will try to conduct the second approach.
