### ISSUE TITLE
Query TweetScraper

### ISSUE THREAD

**Issue by braulley** [jonbakerfish/TweetScraper#33]
Hello, I'm trying to get tweets of bitcoins between certain dates, as in the example: scrapy crawl TweetScraper -a query="bitcoin since:2016-09-01 until:2018-09-01" -a top_tweet=True lang="en",     before there were some 76,000 files, now I ran again and only came 17 files, could you help me?

**Comment by pinwe** [comment]
I'm having a similar issue. Everything was working last as of a couple weeks ago. But now, no matter the number of tweets, the scraper seems to only be returning about 20 results. I thought perhaps it's because twitter changed their url structure, but I checked the urls being requested, and they appeared to be valid and returning results. I'm not a coder, so I didn't investigate beyond that, but I'm guessing there's something triggering scrapy to stop after just one page of results? 
Thanks in advance!

My output below:

scrapy crawl TweetScraper -a query="test until:2017-10-31 since:2017-08-10"
2018-11-01 02:21:29 [scrapy.utils.log] INFO: Scrapy 1.5.0 started (bot: ttss)
2018-11-01 02:21:29 [scrapy.utils.log] INFO: Versions: lxml 4.2.1.0, libxml2 2.9
.5, cssselect 1.0.3, parsel 1.4.0, w3lib 1.19.0, Twisted 18.4.0, Python 3.6.5 (v
3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)], pyOpenSSL
18.0.0 (OpenSSL 1.1.0h  27 Mar 2018), cryptography 2.2.2, Platform Windows-7-6.1
.7601-SP1
2018-11-01 02:21:29 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'bot', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'TweetScraper.spiders', 'SPIDER_MO
DULES': ['TweetScraper.spiders'], 'USER_AGENT': 'email'}
2018-11-01 02:21:29 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2018-11-01 02:21:29 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-11-01 02:21:29 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-11-01 02:21:29 [scrapy.middleware] INFO: Enabled item pipelines:
['TweetScraper.pipelines.SaveToFilePipeline']
2018-11-01 02:21:29 [scrapy.core.engine] INFO: Spider opened
2018-11-01 02:21:29 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pag
es/min), scraped 0 items (at 0 items/min)
2018-11-01 02:21:31 [scrapy.core.engine] INFO: Closing spider (finished)
2018-11-01 02:21:31 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 1172,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 32288,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 2,
 'dupefilter/filtered': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 11, 1, 9, 21, 31, 210164),
 'item_scraped_count': 40,
 'log_count/INFO': 7,
 'request_depth_max': 2,
 'response_received_count': 2,
 'scheduler/dequeued': 2,
 'scheduler/dequeued/memory': 2,
 'scheduler/enqueued': 2,
 'scheduler/enqueued/memory': 2,
 'start_time': datetime.datetime(2018, 11, 1, 9, 21, 29, 640764)}
2018-11-01 02:21:31 [scrapy.core.engine] INFO: Spider closed (finished)

**Comment by manvapatel** [comment]
Hi, I am also having the same problem. Only the first 20 results are scraped, whereas about a few weeks ago it was working perfectly. Any help would be appreciated. Thanks!

**Comment by shiwenThu** [comment]
Maybe my solution will work.
Try to replace the '+' in the min_position with '%2B', it will continue to load the next page.  It worked for me, however it still finished working after getting 8000 tweets,  and I am still looking for the reason. If anybody face this problem but get it solved, please contact me! 


May it help you ~






At 2018-11-01 17:57:06, "manvapatel" <notifications@github.com> wrote:


Hi, I am also having the same problem. Only the first 20 results are scraped, whereas about a few weeks ago it was working perfectly. Any help would be appreciated. Thanks!

**Comment by adrianhp97** [comment]
> Maybe my solution will work. Try to replace the '+' in the min_position with '%2B', it will continue to load the next page. It worked for me, however it still finished working after getting 8000 tweets, and I am still looking for the reason. If anybody face this problem but get it solved, please contact me! May it help you ~ At 2018-11-01 17:57:06, "manvapatel" <notifications@github.com> wrote: Hi, I am also having the same problem. Only the first 20 results are scraped, whereas about a few weeks ago it was working perfectly. Any help would be appreciated. Thanks! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Where can i find the '+' in min_postition? which file?

**Comment by pinwe** [comment]
Thanks shiwen. That solution did seem to work. Though I haven't tested it robustly.
Here's the line I added after line 50 in TweetCrawler.py
min_position = min_position.replace("+","%2B")

**Comment by ganeshknr** [comment]
> Maybe my solution will work. Try to replace the '+' in the min_position with '%2B', it will continue to load the next page. It worked for me, however it still finished working after getting 8000 tweets, and I am still looking for the reason. If anybody face this problem but get it solved, please contact me! May it help you ~ At 2018-11-01 17:57:06, "manvapatel" <notifications@github.com> wrote: Hi, I am also having the same problem. Only the first 20 results are scraped, whereas about a few weeks ago it was working perfectly. Any help would be appreciated. Thanks! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

I also started facing the same issue from few days. Thanks @shiwenThu for providing your solution. By replacing `+` in *min_position* with `%2B` I am able to crawl the data. And I'm not facing the issue which you mentioned (Crawling stopping after 8000 tweets), Today i tested with this and i am able to crawl more than **30,000** tweets (and it is still running), Are you still facing the same?

**Comment by jonbakerfish** [comment]
Fixed in https://github.com/jonbakerfish/TweetScraper/issues/33
