### ISSUE TITLE
"from: {UserId}" doesn't find all tweets of the person, and also returns tweets from others

### ISSUE THREAD

**Issue by yurivict** [jonbakerfish/TweetScraper#53]
I run the command: ```scrapy crawl TweetScraper -a query="from: {UserId}"```

It returns some tweets that don't even contain ```{UserId}``` at all, and not all {UserId}'s tweets are returned.

I think this is a recent regression.

The expected behavior: the above command fetches all tweets with ```{"usernameTweet": "{UserId}", ...```

**Comment by noncomputable** [comment]
Try it without a space after "from:"

**Comment by hamzamogni** [comment]
I noticed weird behavior of the `from` directive in the query. I tested queries directly using Twitter's advanced search tool.
I found that if you insert a space after from ( from: user_id ), the query will return tweets in which the user was mentioned. but if you write it without the space ( from:user_id ), then the query will return tweets sent by that user. 
It is weird, yet I think the issue is with Twitter and not with TweetScraper.
