### ISSUE TITLE
Does this scraper take data legally?

### ISSUE THREAD

**Issue by ardiantovn** [jonbakerfish/TweetScraper#74]
I apologize in advance, I want to ask if this scraper has complied with the rules contained here: https://twitter.com/robots.txt?
I ask questions like this to ensure the legality of the data I get when using this scraper.
Thank you very much

**Comment by MJSchut** [comment]
Let me preface this with: I'm no legal expert. I've been looking into the same thing.

In terms of queries it seems that this package complies with robots.txt, since `Allow: /search?q=%23` is part of robots.txt. I'm pretty sure that the base version does not comply with `Crawl-delay: 1`, so you might need to slow down the rate of requests to comply with this.

However, scraping without prior consent from twitter is in violation of their ToS (https://twitter.com/en/tos, search for scraping). It's unclear to me whether it is legal to still scrape their site even though you didn't agree to their ToS. There doesn't seem to be a consensus, really. 

If you want to be really safe and make sure you take a fully legal route, then use the Twitter API, it's free https://developer.twitter.com/en/docs.

Sorry if this doesn't help much, but the legality seems gray at best.

**Comment by nugrohoav** [comment]
Thank you for the answer...

> NOTE: **crawling** the Services is permissible if done in accordance with the provisions of the robots.txt file, however, **scraping** the Services without the prior consent of Twitter is expressly prohibited

I didn't understand the difference between **crawling** and **scraping**. what is the category of this repository?  Is this repository classified as **crawling** or classified as **scraping?**
